print(" Name : Sanya Srivastava")
print(" Class : IT-B1 ")
print(" URN : 2203889")

print("enter the number of old videos ")
oldVideo = (float(input()))
print("enter the number of new videos ")
newVideo = float(input())
bill=(oldVideo*2.00)+(newVideo*3.00)
print("the total bill is : $",bill)
